import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Header title="Website học Next.js toàn diện" />
          {children}
          <Footer authorName="Kiên (Học viên)"/>
      </body>
    </html>
  );
}